actors:
  doi:
    image_url: /images/actors/doi.jpg
    name: 土井
    url: https://w-doi.tumblr.com/
  peipeipe:
    image_url: /images/actors/peipeipe.jpg
    name: 松下
    url: https://twitter.com/peipeipe
author: 土井と松下
description: WWWでつかまえて は、インターネットが大好きな2人が最近あったことを話すインターネットラジオです。
description_long: インターネットが大好きな2人が最近あったことを話します。やらなくちゃいけないことがたくさんある世の中を生き抜いていく。
email: peipeipe@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-37803028-1
hashtag: wtsuka
itunes_podcast_url: https://podcasts.apple.com/jp/podcast/id1547113514
keywords: anime,manga,technology,otaku,twitter
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: WWWでつかまえて
url: https://www-de-tsukamaete.github.io/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
twitter:
  username: wwwdetsukamaete
  card: summary